import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}></p>
        <ul>
          <li>
            <Link href="/ad-slots">
              <a>View Page with all ad-slots</a>
            </Link>
          </li>
          <li>
            <Link href="/post">
              <a>View Page with 3 ad-slots</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
